Moves to jemalloc
ashfurrow/mastodon pull request #8
Opened 2018-08-22 21:04 UTC by ashfurrow

Moves to Sir Boops' Docker setup for jemalloc. 

I had a very difficult time testing this locally because it required HTTPS – Mastodon's docs specify not to try running Docker locally so we'll have to test it in prod 🙃

2018-08-22 21:05 UTC, ashfurrow commented on Dockerfile
> +EXPOSE 3000 4000
This is my only addition from Sir Boops' Dockerfile, linked to above. Not sure if it's necessary, I'm going to ping them and ask.

2018-08-22 21:37 UTC, Sir-Boops commented
> so we'll have to test it in prod

Masto makes things so easy to test doesn't it! /s

Might want to only test a little piece of it first...like only switching sidekiq over then if that's all good the rest can get moved! :+1:

2018-08-22 21:58 UTC, Sir-Boops reviewed
This should work fine but just be aware

`/mastodon` in this container is just a link `/opt/mastodon`

2018-08-22 22:00 UTC, ashfurrow commented
That's a good idea! The services all _booted_ locally, I just couldn't access them 😅 I have half a mind to spin up a VM somewhere, give it a DNS entry and a lets encrypt cert, and test it there first. We'll seeeeeeeee 😸

2018-08-22 22:01 UTC, ashfurrow commented
> `/mastodon` in this container is just a link `/opt/mastodon`

I did notice these were different from what I had before, do you mean "link to `/opt/mastodon`" on the host VM? Thanks again for answering all my questions 😅

2018-08-22 22:09 UTC, Sir-Boops requested changes
The full path to masto inside the container is
`/opt/mastodon` not the `/mastodon` in the official.

My container DOES link `/mastodon` to `/opt/mastodon`

So these *might* work fine but changing the internal mounts to `/opt/mastodon/public/packs` Might also be needed!

2018-08-22 22:14 UTC, ashfurrow commented
Ah, gotcha! Yup I'll need to change the mounts in docker-compose.yml to point to the full `/opt/mastodon/public/...`.

It looks like [this `COPY` line](https://github.com/ashfurrow/mastodon/pull/8/files#diff-3254677a7917c6c01f55212f86c57fbfR87) might need a change too, but I'll look into what `--from-build-deps` means.

2018-08-22 22:18 UTC, ashfurrow commented
Oh, okay. Hmm – since my code is hosted in `/home/ash/mastodon` (I know, not the best 😬) I'll likely have to update that `COPY` instruction.

2018-08-22 22:21 UTC, Sir-Boops commented
is `/home/ash/mastodon` a built version of masto or just the source?

Like local gems installed yarn packages installed to it

2018-08-22 22:52 UTC, ashfurrow commented
Oh! It's just the source.

2018-08-22 23:23 UTC, Sir-Boops commented
Do you have any custom things in the source or no?

If ya don't then you don't have to use that one :p 

If you do or just want to use something like this ( Haven't tested this but should work for ya! ) -> https://gist.github.com/Sir-Boops/d748a5be6da4f02b41ea8b0f54f9c62e

2018-08-23 00:08 UTC, ashfurrow commented
Cool thanks! I do have some customizations. I appreciate the gist!

2018-08-23 01:20 UTC, ashfurrow commented
SIR BOOPS, IT WORKED

![screen shot 2018-08-22 at 9 19 31 pm](https://user-images.githubusercontent.com/498212/44499249-12a27a80-a651-11e8-9b57-0b637f5f2f74.png)

Thanks again for everything! I've blocked off some time on Saturday to get this from staging onto the actual m.t instance. I'll let you know how it goes 👍

2018-08-23 02:03 UTC, Sir-Boops commented
Yay! Thanks for helping me find those few bugs with it!

And have fun pushing to prod~

2018-08-26 00:42 UTC, ashfurrow commented
Okay I'm happy with this, going to merge. Memory use is still stabilizing and I, uh, committed the sin of forgetting to benchmark memory use in detail before changing something designed to help with memory problems 🙈 I feel a lot more comfortable with these tools and I learned a lot – thanks again for your help!

2018-08-26 00:42 UTC, merged